### ISSUE TITLE
Setting enableAndroidTestCoverage = true causes java.lang.VerifyError at runtime.

### ISSUE THREAD

**Issue by Jonazon** [star-micronics/StarXpand-SDK-Android#18]
## Description

Setting `enableAndroidTestCoverage = true` causes `java.lang.VerifyError` at runtime.

`java.lang.VerifyError: Verifier rejected class com.starmicronics.stario10.stardevicediscoverymanager.c: java.lang.Object com.starmicronics.stario10.stardevicediscoverymanager.c.a(com.starmicronics.stario10.StarDeviceDiscoveryManager$Callback, com.starmicronics.stario10.util.g, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.starmicronics.stario10.stardevicediscoverymanager.c.a(com.starmicronics.stario10.StarDeviceDiscoveryManager$Callback, com.starmicronics.stario10.util.g, kotlin.coroutines.Continuation): [0xE5] expected to be within a catch-all for an instruction where a monitor is held (declaration of 'com.starmicronics.stario10.stardevicediscoverymanager.c' appears in /data/app/~~q8BrsKzOqHykjmPLTlTQAg==/se.jzonite.teststartprinter-zpdDQ9YDEyG_JPFa1Ro9Iw==/base.apk!classes5.dex)
                                                                                                    	at com.starmicronics.stario10.StarDeviceDiscoveryManagerFactory$Companion.create(Unknown Source:56)
                                                                                                    	at com.starmicronics.stario10.StarDeviceDiscoveryManagerFactory$Companion.create(Unknown Source:85)
                                                                                                    	at se.jzonite.teststartprinter.MainActivity.search(MainActivity.kt:88)
                                                                                                    	at se.jzonite.teststartprinter.MainActivity.onCreate(MainActivity.kt:48)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8595)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

I noticed this when updating from 1.0.1 to 1.5.0. The 1.0.1 version doesn't have this problem.

I've uploaded an android starter project experiencing the problem here:
https://github.com/Jonazon/stario-verify-error

**Comment by Tatsuki-Yamamoto2731** [comment]
@Jonazon Thank you for your report.
We will try to recreate the problem.

**Comment by chitho87** [comment]
I got this issue when update from 1.1.0 to 1.7.0 too, have to turn off enableAndroidTestCoverage = false

**Comment by can-miki** [comment]
We apologize for the delay in getting back to you.
After investigation, we found that this issue was caused by the library being protected by "Proguard" from a security perspective.

I don't know what tools or coding you use, but is it possible to skip our API or our test patterns?
I don't think reading into the library to measure the coverage rate is necessary, so I would like you to skip our API.

If you have any comments, please feel free to let me know.
I appreciate your cooperation.

**Comment by Tatsuki-Yamamoto2731** [comment]
As @can-miki said, we found that this issue is caused by the security software that is used in our library. We apologize for the inconvenience, but we would like you to skip loading our libraries when testing. I would like to close this issue, but if you have any comments, please feel free to let me know.
